### ISSUE TITLE
issues with optimizer

### ISSUE THREAD

**Issue by saba-er** [yonsei-icsl/NeuroSpector#1]
First of all, when  neurospector is run without arg "layer", it runs but does not store results in an output scheduling table.
When running with a specific layer ( for example, --layer=CONV_1) it gives an error as follows:
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)

**Comment by pch0561** [comment]
When running with a specific layer, you have to enter the order of the layers, not the name of the layer (for example, if the target layer is 'CONV_1' in resnet50, then --layer=1).

Currently, the output results (optimal scheduling table) of each layer is printed out to terminal. You can store the optimization results by using I/O redirection 
(for example., ./neurospector -r=optimizer -a=configs/accelerators/eyeriss.cfg -n=configs/networks/resnet50.cfg -d=fixed -o=bottom-up -m=energy > output.txt). 
We are preparing to add the function that stores running results as an output file.

**Comment by pch0561** [comment]
When running with a specific layer, you have to enter the order of the layers, not the name of the layer (for example, if the target layer is 'CONV_1' in resnet50, then --layer=1).

Currently, the output results (optimal scheduling table) of each layer is printed out to terminal. You can store the optimization results by using I/O redirection 
(for example., ./neurospector -r=optimizer -a=configs/accelerators/eyeriss.cfg -n=configs/networks/resnet50.cfg -d=fixed -o=bottom-up -m=energy > output.txt). 
We are preparing to add the function that stores running results as an output file.

**Comment by saba-er** [comment]
Thanks!
If the output results of the optimizer are dumped into output.txt (as you suggest), then would it possible to give it directly as input to analyzer? (I am just looking into the dumped txt file and it does not look like the format of input to analyzer (such as  eyeriss_sample.cfg that you provided in the repo))

**Comment by saba-er** [comment]
Another question is about the frequency of eyeriss. In the original paper where eyeriss was introduced, the frequency is up to 250 MHZ. Why do you set it to 800 MHZ in your repo?

**Comment by pch0561** [comment]
NeuroSpector currently not support the way to directly use optimization results as an input of analyzer. 
(If I understand correctly) I recommend to make an input scheduling table by referring to the scheduling table in output txt file. 
 The scheduling tables in optimizer may look little different, but the row and column order of the table is the same. (I attach the capture image as an example. I hope this helps)

![image](https://user-images.githubusercontent.com/37764489/185756927-653fb866-98ad-48fa-92c3-6b69e78fc16a.png)


And 800 MHz is a typo that occurred while creating an example config. Thank you for catching it.

**Comment by saba-er** [comment]
I appreciate it very much for attending to my questions. 
So what do you think the clock frequency should be changed to? 250 MHZ?
Then, what would be the length of a "cycle" in the simulator?

**Comment by pch0561** [comment]
Thank you for your interest in NeuroSpector.
 I think the clock frequency doesn't necessarily have to be 250MHz (the original paper says that the clock frequency is between 100 and 250).
 The length of a cycle of provided example has been set assuming that the clock frequency is 200MHz. So if you want to test about eyeriss, I think it is enough to test the performance (or energy) with the provided config file.
